cloud:
  aws:
    credentials: 
      access-key: REDACTED_KEY 
      secret-key: REDACTED_SECRET
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: vanguardlionwebsitetest

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB


